/**
 * Generate the static, email-safe HTML templates for backend mail.
 *
 * Email clients strip JavaScript and ignore most modern CSS, so the
 * app's Vue/Vuetify components cannot be reused at runtime. Instead we
 * author email-safe HTML here (table layout, inline styles, no JS) and
 * bake in the shared design tokens from `src/theme/tokens.ts`, so a
 * theme change in the app propagates to the email on the next run.
 *
 * The output files are pure `string.Template` shells: only token-driven
 * colours/fonts are interpolated here; every `$placeholder` is left
 * literal for the Python renderer to fill at send time.
 *
 * Run via `npm run build:email` (or `task build:email`). The artifacts
 * are committed so the backend builds and tests without a Node
 * toolchain.
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

import { fonts, meepleTimeTokens } from '../src/theme/tokens.ts'

// Match the app default: the "Warmer Dark" night theme.
const c = meepleTimeTokens.themes.meepletimeDark

const bodyBg = c.background
const cardBg = c['surface-container']
const text = c['on-surface']
const muted = c['on-surface-variant']
const primary = c.primary
const onPrimary = c['on-primary']
const tertiary = c.tertiary
const border = c['outline-variant']

// Keep the token's family name, but add web-safe fallbacks because
// Gmail/Outlook strip @import/<link> web fonts.
const family = (stack: string) => stack.split(',')[0].trim()
const bodyFont =
  `${family(fonts.base)}, -apple-system, BlinkMacSystemFont, ` +
  `'Segoe UI', Roboto, Helvetica, Arial, sans-serif`
const displayFont = `${family(fonts.display)}, Georgia, 'Times New Roman', serif`

const banner =
  '<!-- GENERATED by frontend/email/build.ts — do not edit; ' +
  'run `task build:email` -->\n'

const shell = `${banner}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="color-scheme" content="dark light" />
    <meta name="supported-color-schemes" content="dark light" />
    <title>MeepleTime</title>
    <style>
      @media (max-width: 600px) {
        .mt-card { width: 100% !important; }
      }
    </style>
  </head>
  <body style="margin:0; padding:0; background-color:${bodyBg};
    -webkit-text-size-adjust:100%;">
    <div style="display:none; max-height:0; overflow:hidden;
      opacity:0; color:${bodyBg};">$preheader</div>
    <table role="presentation" width="100%" cellpadding="0"
      cellspacing="0" style="background-color:${bodyBg};
      border-collapse:collapse;">
      <tr>
        <td align="center" style="padding:24px 12px;">
          <table role="presentation" class="mt-card" width="600"
            cellpadding="0" cellspacing="0" style="width:600px;
            max-width:600px; background-color:${cardBg};
            border-radius:16px; overflow:hidden;
            border-collapse:separate;">
            $hero
            <tr>
              <td style="padding:28px 32px;">$content</td>
            </tr>
            <tr>
              <td style="padding:0 32px 28px; font-family:${bodyFont};
                font-size:12px; line-height:1.5; color:${muted};">
                You are receiving this email from MeepleTime. Manage
                notifications in your account settings.
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>
`

const heroImage = `${banner}<tr>
  <td style="padding:0; font-size:0; line-height:0;">
    <img src="cid:hero" alt="$alt" width="600" style="display:block;
      width:100%; max-width:600px; height:auto; border:0;" />
  </td>
</tr>
`

const heroFallback = `${banner}<tr>
  <td bgcolor="${primary}" align="center" height="132"
    style="height:132px; background-color:${primary};
    background-image:linear-gradient(135deg, ${primary}, ${tertiary});">
    <div style="font-family:${displayFont}; font-size:44px;
      font-weight:700; color:#ffffff; line-height:132px;
      letter-spacing:1px;">$initials</div>
  </td>
</tr>
`

const cta = `<table role="presentation" cellpadding="0" cellspacing="0"
  style="margin:8px 0 4px;">
  <tr>
    <td bgcolor="${primary}" style="border-radius:12px;">
      <a href="$cta_url" style="display:inline-block; padding:12px 22px;
        font-family:${bodyFont}; font-size:15px; font-weight:600;
        color:${onPrimary}; text-decoration:none;
        border-radius:12px;">$cta_label</a>
    </td>
  </tr>
</table>`

const heading = `<h1 style="margin:0 0 12px; font-family:${displayFont};
  font-size:22px; line-height:1.25; color:${text};">$heading</h1>`

const lead = `<p style="margin:0 0 20px; font-family:${bodyFont};
  font-size:15px; line-height:1.55; color:${muted};">$lead</p>`

const notificationBody = `${banner}${heading}
${lead}
$detail
${cta}
`

const confirmationBody = `${banner}${heading}
${lead}
${cta}
<p style="margin:20px 0 0; font-family:${bodyFont}; font-size:13px;
  line-height:1.5; color:${muted};">$note</p>
`

const dayList = `${banner}<table role="presentation" width="100%"
  cellpadding="0" cellspacing="0"
  style="margin:0 0 20px; border-collapse:collapse;">
$rows
</table>
`

const dayRow = `${banner}<tr>
  <td style="padding:8px 0; border-bottom:1px solid ${border};
    font-family:${bodyFont}; font-size:14px; color:${text};">
    <span style="color:${muted};">$day</span>&nbsp;&nbsp;<strong>$phrase</strong>
  </td>
</tr>
`

const files: Record<string, string> = {
  'shell.html': shell,
  'hero_image.html': heroImage,
  'hero_fallback.html': heroFallback,
  'notification_body.html': notificationBody,
  'confirmation_body.html': confirmationBody,
  'day_list.html': dayList,
  'day_row.html': dayRow,
}

const outDir = fileURLToPath(
  new URL(
    '../../backend/src/app/services/notifications/templates/',
    import.meta.url,
  ),
)

await mkdir(outDir, { recursive: true })
for (const [name, content] of Object.entries(files)) {
  await writeFile(outDir + name, content, 'utf-8')
  console.log(`wrote ${name}`)
}
