/**
 * Generate the Keycloak theme's design-token CSS from the shared tokens.
 *
 * The `meepletime` Keycloak theme (login + account FreeMarker templates and
 * their `login.css` / `account.css`) is styled entirely through the `--mt-*`
 * CSS custom properties declared in `brand-tokens.css`. Those used to be
 * hand-maintained and drifted from the app. This generator bakes the same
 * shared design tokens from `src/theme/tokens.ts` into `brand-tokens.css`, so a
 * theme change in the app propagates to the Keycloak login/account pages on the
 * next run — mirroring how `email/build.ts` feeds the mail templates.
 *
 * Only colours and font families are token-driven. The shape / depth tokens
 * (radii, glass blur, shadow) are Keycloak-specific and have no counterpart in
 * the app tokens, so they stay as constants here.
 *
 * Run via `npm run build:keycloak` (or `task build:keycloak`). The generated
 * files are committed so the mounted theme needs no build step at deploy time.
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

import { fonts, meepleTimeTokens } from '../src/theme/tokens.ts'

// Match the app default: the "Warmer Dark" night theme.
const c = meepleTimeTokens.themes.meepletimeDark

// Map the app's semantic dark-theme tokens onto the Keycloak `--mt-*` names
// the theme CSS consumes. Kept visually close to the previous hand-tuned
// values; the submit button stays a peach→terracotta gradient by mapping
// `--mt-primary` to the peach accent and `--mt-primary-deep` to the filled CTA.
const colors: Record<string, string> = {
  '--mt-surface': c.background,
  '--mt-surface-high': c['surface-container'],
  '--mt-surface-highest': c['surface-container-high'],
  '--mt-text': c['on-surface'],
  '--mt-text-muted': c['on-surface-variant'],
  '--mt-outline': c['outline-variant'],
  '--mt-primary': c['primary-accent'],
  '--mt-primary-deep': c.primary,
  '--mt-on-primary': c['on-primary'],
  '--mt-error': c.error,
  '--mt-error-bg': c['error-container'],
}

// Font families come from the shared tokens; the theme CSS references these
// via `var(--mt-font-base)` / `var(--mt-font-display)`.
const fontVars: Record<string, string> = {
  '--mt-font-base': fonts.base,
  '--mt-font-display': fonts.display,
}

// Keycloak-specific shape / depth tokens — no app-token counterpart.
const shape: Record<string, string> = {
  '--mt-shadow': 'rgba(0, 0, 0, 0.35)',
  '--mt-card-radius': '1.25rem',
  '--mt-field-radius': '0.65rem',
  '--mt-button-radius': '0.7rem',
  '--mt-glass-blur': '18px',
}

const block = (vars: Record<string, string>) =>
  Object.entries(vars)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n')

// Web-font imports for the families above. Emitted here so a font swap in the
// tokens is a one-line change in this generator alongside the family value.
const imports = [
  "@import url('https://fonts.googleapis.com/css2?family=Noto+Serif:wght@400;700&display=swap');",
  "@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap');",
].join('\n')

const css = `/* GENERATED by frontend/keycloak/build.ts — do not edit; run \`task build:keycloak\` */
${imports}

:root {
${block(colors)}

${block(fontVars)}

${block(shape)}
}
`

// The login and account themes share one identical token file.
const targets = [
  '../../assets/keycloak/themes/meepletime/login/resources/css/brand-tokens.css',
  '../../assets/keycloak/themes/meepletime/account/resources/css/brand-tokens.css',
]

for (const rel of targets) {
  const path = fileURLToPath(new URL(rel, import.meta.url))
  await mkdir(fileURLToPath(new URL('.', new URL(rel, import.meta.url))), {
    recursive: true,
  })
  await writeFile(path, css, 'utf-8')
  console.log(`wrote ${rel}`)
}
